# Basic
title: webbleen
subtitle: A blog-orientation theme for Jekyll
welcome_message: <a href="https://github.com/webbleen/wno-jekyll" target="_blank">Download the theme</a>
description: Wno Jekyll is a port of my Ghost theme wno.
creator: <a href="http://webbleen.com">@webbleen</a>

url: "http://webbleen.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.webbleen.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: wno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: webbleen
    github: webbleen
    twitter: webbleen
    gplus: 107108267983477358170
    mail: webbleen@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
